#!/usr/bin/env bash
# Catppuccin Mocha — warm pastel theme
# https://github.com/catppuccin/catppuccin

THEME_NAME="Catppuccin Mocha"

# Backgrounds
THEME_BG="#1e1e2e"
THEME_BG_ALT="#181825"
THEME_BG_HIGHLIGHT="#313244"

# Foregrounds
THEME_FG="#cdd6f4"
THEME_FG_DIM="#6c7086"
THEME_FG_BRIGHT="#f5e0dc"

# Accent
THEME_ACCENT="#cba6f7"
THEME_ACCENT_BRIGHT="#f5c2e7"

# Palette
THEME_RED="#f38ba8"
THEME_GREEN="#a6e3a1"
THEME_YELLOW="#f9e2af"
THEME_BLUE="#89b4fa"
THEME_MAGENTA="#cba6f7"
THEME_CYAN="#94e2d5"

# Borders
THEME_BORDER="#313244"
THEME_BORDER_ACTIVE="#cba6f7"

# Terminal ANSI (0-15)
THEME_ANSI_BLACK="#1e1e2e"
THEME_ANSI_RED="#f38ba8"
THEME_ANSI_GREEN="#a6e3a1"
THEME_ANSI_YELLOW="#f9e2af"
THEME_ANSI_BLUE="#89b4fa"
THEME_ANSI_MAGENTA="#cba6f7"
THEME_ANSI_CYAN="#94e2d5"
THEME_ANSI_WHITE="#cdd6f4"
THEME_ANSI_BRIGHT_BLACK="#6c7086"
THEME_ANSI_BRIGHT_RED="#f38ba8"
THEME_ANSI_BRIGHT_GREEN="#a6e3a1"
THEME_ANSI_BRIGHT_YELLOW="#f9e2af"
THEME_ANSI_BRIGHT_BLUE="#89b4fa"
THEME_ANSI_BRIGHT_MAGENTA="#f5c2e7"
THEME_ANSI_BRIGHT_CYAN="#94e2d5"
THEME_ANSI_BRIGHT_WHITE="#f5e0dc"

# GTK/Qt theme hints
THEME_GTK_THEME="Adwaita-dark"
THEME_ICON_THEME="Adwaita"
THEME_CURSOR_THEME="Adwaita"
THEME_CURSOR_SIZE="24"
