#!/usr/bin/env bash
# Dracula — classic dark theme
# https://draculatheme.com

THEME_NAME="Dracula"

# Backgrounds
THEME_BG="#282a36"
THEME_BG_ALT="#21222c"
THEME_BG_HIGHLIGHT="#44475a"

# Foregrounds
THEME_FG="#f8f8f2"
THEME_FG_DIM="#6272a4"
THEME_FG_BRIGHT="#ffffff"

# Accent
THEME_ACCENT="#bd93f9"
THEME_ACCENT_BRIGHT="#d6acff"

# Palette
THEME_RED="#ff5555"
THEME_GREEN="#50fa7b"
THEME_YELLOW="#f1fa8c"
THEME_BLUE="#6272a4"
THEME_MAGENTA="#ff79c6"
THEME_CYAN="#8be9fd"

# Borders
THEME_BORDER="#44475a"
THEME_BORDER_ACTIVE="#bd93f9"

# Terminal ANSI (0-15)
THEME_ANSI_BLACK="#282a36"
THEME_ANSI_RED="#ff5555"
THEME_ANSI_GREEN="#50fa7b"
THEME_ANSI_YELLOW="#f1fa8c"
THEME_ANSI_BLUE="#6272a4"
THEME_ANSI_MAGENTA="#ff79c6"
THEME_ANSI_CYAN="#8be9fd"
THEME_ANSI_WHITE="#f8f8f2"
THEME_ANSI_BRIGHT_BLACK="#6272a4"
THEME_ANSI_BRIGHT_RED="#ff6e6e"
THEME_ANSI_BRIGHT_GREEN="#69ff94"
THEME_ANSI_BRIGHT_YELLOW="#ffffa5"
THEME_ANSI_BRIGHT_BLUE="#d6acff"
THEME_ANSI_BRIGHT_MAGENTA="#ff92df"
THEME_ANSI_BRIGHT_CYAN="#a4ffff"
THEME_ANSI_BRIGHT_WHITE="#ffffff"

# GTK/Qt theme hints
THEME_GTK_THEME="Adwaita-dark"
THEME_ICON_THEME="Adwaita"
THEME_CURSOR_THEME="Adwaita"
THEME_CURSOR_SIZE="24"
